export class Candidate {
  id: string;
  email: string;
  skypeAddress: string;
  cellphone: string;
  linkedinAddress: string;
  city: string;
  state: string;
  portfolio: string;
  fourHours: boolean;
  fourSixHours: boolean;
  sixEightHours: boolean;
  eightHours: boolean;
  hoursOnWeekends: boolean;
  morning: boolean;
  afternoon: boolean;
  night: boolean;
  dawn: boolean;
  comercial: boolean;
  salary: number;
  crudLink: string;
  recipient: string;
  cpfRecipient: string;
  bankName: string;
  agency: string;
  account: string;
  chain: boolean;
  savings: boolean;
}
