// <auto-generated />
using EasyCrud.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EasyCrud.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181008212902_AlterTables_DecimalSalary")]
    partial class AlterTables_DecimalSalary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyCrud.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Afternoon");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("CPFRecipient")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("Chain");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("Comercial");

                    b.Property<string>("CrudLink");

                    b.Property<bool>("Dawn");

                    b.Property<bool>("EightHours");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("FourHours");

                    b.Property<bool>("FourSixHours");

                    b.Property<bool>("HoursOnWeekends");

                    b.Property<Guid>("KnowledgeId");

                    b.Property<string>("LinkedinAddress")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Morning");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("Night");

                    b.Property<string>("Portfolio")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Salary");

                    b.Property<bool>("Savings");

                    b.Property<bool>("SixEightHours");

                    b.Property<string>("SkypeAddress");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("EasyCrud.Domain.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Android");

                    b.Property<int>("Angular");

                    b.Property<int>("Asp");

                    b.Property<int>("Bootstrap");

                    b.Property<int?>("C");

                    b.Property<int?>("Cake");

                    b.Property<int?>("Cplusplus");

                    b.Property<int?>("Css");

                    b.Property<int?>("Django");

                    b.Property<int?>("Html");

                    b.Property<int?>("Illustrator");

                    b.Property<int>("Ionic");

                    b.Property<int>("Ios");

                    b.Property<int?>("Java");

                    b.Property<int>("Jquery");

                    b.Property<int?>("Magento");

                    b.Property<int?>("MySql");

                    b.Property<string>("Others")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasMaxLength(300);

                    b.Property<int?>("Photoshop");

                    b.Property<int>("Php");

                    b.Property<int?>("Python");

                    b.Property<int?>("Ruby");

                    b.Property<int?>("Salesforce");

                    b.Property<int?>("Seo");

                    b.Property<int?>("SqlServer");

                    b.Property<int>("Wordpress");

                    b.HasKey("Id");

                    b.ToTable("Knowledges");
                });

            modelBuilder.Entity("EasyCrud.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("EasyCrud.Domain.Entities.Knowledge", "Knowledge")
                        .WithMany()
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
